# This is a basic workflow to help you get started with Actions
name: "Release"

# Controls when the workflow will run
on:
  release:
    types: # This configuration does not affect the page_build event above
      - prereleased
      - released

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - shell: pwsh
        name: Run tests
        run: |
          Push-Location ./tests;
          ./build.ps1 -Script "./tests.cake" -Verbosity Diagnostic;
          Pop-Location

      - shell: pwsh
        name: Set package version
        id: set-version
        run: |
          $version = ("${{ github.event.release.tag_name }}" -replace "v(\d+.\d+.\d+.*)", '$1')
          echo "BUILD_VERSION=${version}" >> $Env:GITHUB_ENV

      - shell: pwsh
        name: Pack the package
        run: nuget pack ./Cake.Sitecore.nuspec -Version "${{ env.BUILD_VERSION }}"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "Cake.Sitecore (${{ env.BUILD_VERSION }})"
          path: |
            Cake.Sitecore.*.nupkg

      - shell: pwsh
        name: Publish the package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          nuget push "./Cake.Sitecore.${{ env.BUILD_VERSION }}.nupkg" -ApiKey "${{ env.NUGET_API_KEY }}" -Source https://api.nuget.org/v3/index.json -SkipDuplicate
