# This is a basic workflow to help you get started with Actions
name: "Unpublish"

# Controls when the workflow will run
on:
  release:
    types: # This configuration does not affect the page_build event above
      - deleted
      - unpublished

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unpublish:
    runs-on: windows-latest

    steps:
      - shell: pwsh
        name: Unpublish the package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          echo "TODO: unpublish NuGet package"